DROP TABLE estado_mensaje CASCADE CONSTRAINTS;
DROP TABLE mensaje CASCADE CONSTRAINTS;
DROP TABLE participante_chat CASCADE CONSTRAINTS;
DROP TABLE chat CASCADE CONSTRAINTS;
DROP TABLE usuario CASCADE CONSTRAINTS;
DROP TABLE rol CASCADE CONSTRAINTS;
DROP TABLE tipo_chat CASCADE CONSTRAINTS;
DROP TABLE tipo_mensaje CASCADE CONSTRAINTS;
DROP TABLE estado CASCADE CONSTRAINTS;
DROP TABLE estado_usuario CASCADE CONSTRAINTS;

CREATE TABLE estado_usuario (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR2(50) NOT NULL,
    activo CHAR(1) DEFAULT 'S'
);

CREATE TABLE estado (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    decripcion VARCHAR2(50) NOT NULL,
    activo CHAR(1) DEFAULT 'S'
);

CREATE TABLE tipo_mensaje (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR2(50) NOT NULL,
    activo CHAR(1) DEFAULT 'S'
);

CREATE TABLE tipo_chat (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR2(50) NOT NULL,
    activo CHAR(1) DEFAULT 'S'
);

CREATE TABLE rol (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR2(50) NOT NULL,
    activo CHAR(1) DEFAULT 'S'
);

CREATE TABLE usuario (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    numero_telefonico VARCHAR2(20) NOT NULL UNIQUE,
    nombre VARCHAR2(100) NOT NULL,
    foto_perfil_url VARCHAR2(500),
    fecha_registro TIMESTAMP NOT NULL,
    ultimo_acceso TIMESTAMP DEFAULT SYSTIMESTAMP,
    activo CHAR(1) DEFAULT 'S',
    estado_usuario_id NUMBER REFERENCES estado_usuario(id) NOT NULL
);

CREATE TABLE chat (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tipo_chat_id NUMBER REFERENCES tipo_chat(id) NOT NULL,
    nombre_grupo VARCHAR2(100),
    foto_grupo_url VARCHAR2(500),
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    activo CHAR(1) DEFAULT 'S'
);

CREATE TABLE participante_chat (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    chat_id NUMBER REFERENCES chat(id) UNIQUE NOT NULL,
    usuario_id NUMBER REFERENCES usuario(id) UNIQUE NOT NULL,
    rol_id NUMBER REFERENCES rol(id) NOT NULL,
    fecha_union TIMESTAMP DEFAULT SYSTIMESTAMP,
    silenciado CHAR(1) DEFAULT 'S' NOT NULL,
    activo CHAR(1) DEFAULT 'S' NOT NULL
);

CREATE TABLE mensaje (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    chat_id NUMBER REFERENCES chat(id) NOT NULL,
    usuario_id NUMBER REFERENCES usuario(id) NOT NULL,
    contenido CLOB NOT NULL,
    tipo_mensaje_id NUMBER REFERENCES tipo_mensaje(id) NOT NULL,
    fecha_envio TIMESTAMP DEFAULT SYSTIMESTAMP,
    eliminado CHAR(1) DEFAULT 'N'
);

CREATE TABLE estado_mensaje (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    mensaje_id NUMBER REFERENCES mensaje(id) NOT NULL,
    usuario_id NUMBER REFERENCES usuario(id) NOT NULL,
    estado_id NUMBER REFERENCES estado(id) NOT NULL,
    fecha_estado TIMESTAMP DEFAULT SYSTIMESTAMP
);